branches:
  only:
    - master
language: go
go:
  - 1.6
  - tip
before_install:
  - go get -v github.com/github/git-lfs
  - git lfs install
  - git lfs pull
install:
  - go get -v github.com/spf13/hugo
  - go get -v github.com/jessecarl/portfolio-images
  - npm install
script:
  - gulp
  - portfolio-images -i "$TRAVIS_BUILD_DIR/static/img/photo/*.jpg" -o "$TRAVIS_BUILD_DIR/static/img/responsive/photo" -q 80 -s "-sm:300,-md:600,-lg:900,-xl:1200,-full:1800"
  - portfolio-images -i "$TRAVIS_BUILD_DIR/static/img/print/*.jpg" -o "$TRAVIS_BUILD_DIR/static/img/responsive/print" -q 80 -s "-sm:300,-md:600,-lg:900,-xl:1200,-full:1800"
  - hugo --verbose
after_success: s3_website push
