# Welcome to Jekyll!
title: Jesse Allen
email: jesse@jessecarl.com
description: > # this means to ignore newlines until "baseurl:"
  
url: "http://www.jessecarl.com" # the base hostname & protocol for your site
twitter_username: jessecarl
github_username:  jessecarl

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
excerpt_separator: <!--more-->
sass:
  sass_dir: _sass
  style: compressed
