# Welcome to Jekyll!
title: Jesse Allen
email: jesse@jessecarl.com
tagline: A Maker of… Code • Music • Art
description: > # this means to ignore newlines until "baseurl:"
  
url: "http://www.jessecarl.com" # the base hostname & protocol for your site
twitter_username: jessecarl
github_username:  jessecarl
logo_url: http://www.gravatar.com/avatar/055c5f84f186142804fba9393a35ca69

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
excerpt_separator: <!--more-->
sass:
  sass_dir: _sass
  style: compressed
